# Generated by Django 3.0.6 on 2020-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(blank=True, upload_to='meals/'),
        ),
    ]
