# Generated by Django 3.0.6 on 2020-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200627_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(),
        ),
    ]
